HTMLElement = function HTMLElement (){environment.error()};
environment.safefunction(HTMLElement);
environment.rename(HTMLElement);

Object.defineProperty(HTMLElement.prototype,"title",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"lang",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"translate",{value: true,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"dir",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"hidden",{value: false,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"accessKey",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"draggable",{value: false,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"spellcheck",{value: true,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"autocapitalize",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"contentEditable",{value: `inherit`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"isContentEditable",{value: false,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"inputMode",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"offsetParent",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"offsetTop",{value: 0,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"offsetLeft",{value: 0,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"offsetWidth",{value: 987,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"offsetHeight",{value: 150,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"style",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"innerText",{value: `当前您正在使用隐身窗口

隐身窗口可以：

上网不留痕迹，隐身模式上网不留任何记录

小号多开，新建隐身窗口再打开网站小号，不串号

隐身窗口不会记录任何上网痕迹，但会保留您下载的文件和添加的收藏。

隐身窗口会默认禁用所有扩展以保护隐私，如有需启用的扩展，可以在扩展管理页面设置。`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"outerText",{value: `当前您正在使用隐身窗口

隐身窗口可以：

上网不留痕迹，隐身模式上网不留任何记录

小号多开，新建隐身窗口再打开网站小号，不串号

隐身窗口不会记录任何上网痕迹，但会保留您下载的文件和添加的收藏。

隐身窗口会默认禁用所有扩展以保护隐私，如有需启用的扩展，可以在扩展管理页面设置。`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onabort",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onblur",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncancel",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncanplay",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncanplaythrough",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onchange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onclick",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onclose",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncontextmenu",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncuechange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondblclick",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondrag",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondragend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondragenter",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondragleave",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondragover",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondragstart",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondrop",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ondurationchange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onemptied",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onended",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onerror",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onfocus",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onformdata",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oninput",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oninvalid",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onkeydown",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onkeypress",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onkeyup",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onload",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onloadeddata",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onloadedmetadata",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onloadstart",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmousedown",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmouseenter",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmouseleave",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmousemove",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmouseout",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmouseover",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmouseup",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onmousewheel",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpause",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onplay",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onplaying",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onprogress",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onratechange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onreset",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onresize",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onscroll",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onseeked",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onseeking",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onselect",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onstalled",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onsubmit",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onsuspend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ontimeupdate",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ontoggle",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onvolumechange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwaiting",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwebkitanimationend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwebkitanimationiteration",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwebkitanimationstart",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwebkittransitionend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onwheel",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onauxclick",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ongotpointercapture",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onlostpointercapture",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerdown",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointermove",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerup",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointercancel",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerover",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerout",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerenter",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerleave",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onselectstart",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onselectionchange",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onanimationend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onanimationiteration",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onanimationstart",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"ontransitionend",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncopy",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"oncut",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpaste",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"dataset",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"nonce",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"autofocus",{value: false,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"tabIndex",{value: -1,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"attachInternals",{value: function attachInternals(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"blur",{value: function blur(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"click",{value: function click(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"focus",{value: function focus(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"onpointerrawupdate",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(HTMLElement.prototype,"enterKeyHint",{value: ``,writable:undefined,enumerable:true,configurable:true});

environment.safefunction(Element.prototype.after);
environment.rename(Element.prototype.after,"after");
environment.safefunction(Element.prototype.animate);
environment.rename(Element.prototype.animate,"animate");
environment.safefunction(Element.prototype.append);
environment.rename(Element.prototype.append,"append");
environment.safefunction(Element.prototype.attachShadow);
environment.rename(Element.prototype.attachShadow,"attachShadow");
environment.safefunction(Element.prototype.before);
environment.rename(Element.prototype.before,"before");
environment.safefunction(Element.prototype.closest);
environment.rename(Element.prototype.closest,"closest");
environment.safefunction(Element.prototype.computedStyleMap);
environment.rename(Element.prototype.computedStyleMap,"computedStyleMap");
environment.safefunction(Element.prototype.getAttribute);
environment.rename(Element.prototype.getAttribute,"getAttribute");
environment.safefunction(Element.prototype.getAttributeNS);
environment.rename(Element.prototype.getAttributeNS,"getAttributeNS");
environment.safefunction(Element.prototype.getAttributeNames);
environment.rename(Element.prototype.getAttributeNames,"getAttributeNames");
environment.safefunction(Element.prototype.getAttributeNode);
environment.rename(Element.prototype.getAttributeNode,"getAttributeNode");
environment.safefunction(Element.prototype.getAttributeNodeNS);
environment.rename(Element.prototype.getAttributeNodeNS,"getAttributeNodeNS");
environment.safefunction(Element.prototype.getBoundingClientRect);
environment.rename(Element.prototype.getBoundingClientRect,"getBoundingClientRect");
environment.safefunction(Element.prototype.getClientRects);
environment.rename(Element.prototype.getClientRects,"getClientRects");
environment.safefunction(Element.prototype.getElementsByClassName);
environment.rename(Element.prototype.getElementsByClassName,"getElementsByClassName");
environment.safefunction(Element.prototype.getElementsByTagName);
environment.rename(Element.prototype.getElementsByTagName,"getElementsByTagName");
environment.safefunction(Element.prototype.getElementsByTagNameNS);
environment.rename(Element.prototype.getElementsByTagNameNS,"getElementsByTagNameNS");
environment.safefunction(Element.prototype.hasAttribute);
environment.rename(Element.prototype.hasAttribute,"hasAttribute");
environment.safefunction(Element.prototype.hasAttributeNS);
environment.rename(Element.prototype.hasAttributeNS,"hasAttributeNS");
environment.safefunction(Element.prototype.hasAttributes);
environment.rename(Element.prototype.hasAttributes,"hasAttributes");
environment.safefunction(Element.prototype.hasPointerCapture);
environment.rename(Element.prototype.hasPointerCapture,"hasPointerCapture");
environment.safefunction(Element.prototype.insertAdjacentElement);
environment.rename(Element.prototype.insertAdjacentElement,"insertAdjacentElement");
environment.safefunction(Element.prototype.insertAdjacentHTML);
environment.rename(Element.prototype.insertAdjacentHTML,"insertAdjacentHTML");
environment.safefunction(Element.prototype.insertAdjacentText);
environment.rename(Element.prototype.insertAdjacentText,"insertAdjacentText");
environment.safefunction(Element.prototype.matches);
environment.rename(Element.prototype.matches,"matches");
environment.safefunction(Element.prototype.prepend);
environment.rename(Element.prototype.prepend,"prepend");
environment.safefunction(Element.prototype.querySelector);
environment.rename(Element.prototype.querySelector,"querySelector");
environment.safefunction(Element.prototype.querySelectorAll);
environment.rename(Element.prototype.querySelectorAll,"querySelectorAll");
environment.safefunction(Element.prototype.releasePointerCapture);
environment.rename(Element.prototype.releasePointerCapture,"releasePointerCapture");
environment.safefunction(Element.prototype.remove);
environment.rename(Element.prototype.remove,"remove");
environment.safefunction(Element.prototype.removeAttribute);
environment.rename(Element.prototype.removeAttribute,"removeAttribute");
environment.safefunction(Element.prototype.removeAttributeNS);
environment.rename(Element.prototype.removeAttributeNS,"removeAttributeNS");
environment.safefunction(Element.prototype.removeAttributeNode);
environment.rename(Element.prototype.removeAttributeNode,"removeAttributeNode");
environment.safefunction(Element.prototype.replaceWith);
environment.rename(Element.prototype.replaceWith,"replaceWith");
environment.safefunction(Element.prototype.requestFullscreen);
environment.rename(Element.prototype.requestFullscreen,"requestFullscreen");
environment.safefunction(Element.prototype.requestPointerLock);
environment.rename(Element.prototype.requestPointerLock,"requestPointerLock");
environment.safefunction(Element.prototype.scroll);
environment.rename(Element.prototype.scroll,"scroll");
environment.safefunction(Element.prototype.scrollBy);
environment.rename(Element.prototype.scrollBy,"scrollBy");
environment.safefunction(Element.prototype.scrollIntoView);
environment.rename(Element.prototype.scrollIntoView,"scrollIntoView");
environment.safefunction(Element.prototype.scrollIntoViewIfNeeded);
environment.rename(Element.prototype.scrollIntoViewIfNeeded,"scrollIntoViewIfNeeded");
environment.safefunction(Element.prototype.scrollTo);
environment.rename(Element.prototype.scrollTo,"scrollTo");
environment.safefunction(Element.prototype.setAttribute);
environment.rename(Element.prototype.setAttribute,"setAttribute");
environment.safefunction(Element.prototype.setAttributeNS);
environment.rename(Element.prototype.setAttributeNS,"setAttributeNS");
environment.safefunction(Element.prototype.setAttributeNode);
environment.rename(Element.prototype.setAttributeNode,"setAttributeNode");
environment.safefunction(Element.prototype.setAttributeNodeNS);
environment.rename(Element.prototype.setAttributeNodeNS,"setAttributeNodeNS");
environment.safefunction(Element.prototype.setPointerCapture);
environment.rename(Element.prototype.setPointerCapture,"setPointerCapture");
environment.safefunction(Element.prototype.toggleAttribute);
environment.rename(Element.prototype.toggleAttribute,"toggleAttribute");
environment.safefunction(Element.prototype.webkitMatchesSelector);
environment.rename(Element.prototype.webkitMatchesSelector,"webkitMatchesSelector");
environment.safefunction(Element.prototype.webkitRequestFullScreen);
environment.rename(Element.prototype.webkitRequestFullScreen,"webkitRequestFullScreen");
environment.safefunction(Element.prototype.webkitRequestFullscreen);
environment.rename(Element.prototype.webkitRequestFullscreen,"webkitRequestFullscreen");
environment.safefunction(Element.prototype.getAnimations);
environment.rename(Element.prototype.getAnimations,"getAnimations");
environment.safefunction(Element.prototype.replaceChildren);
environment.rename(Element.prototype.replaceChildren,"replaceChildren");
environment.safefunction(HTMLElement.prototype.attachInternals);
environment.rename(HTMLElement.prototype.attachInternals,"attachInternals");
environment.safefunction(HTMLElement.prototype.blur);
environment.rename(HTMLElement.prototype.blur,"blur");
environment.safefunction(HTMLElement.prototype.click);
environment.rename(HTMLElement.prototype.click,"click");
environment.safefunction(HTMLElement.prototype.focus);
environment.rename(HTMLElement.prototype.focus,"focus");
Object.setPrototypeOf(HTMLElement.prototype, Element.prototype);
