Navigator = function Navigator (){environment.error()};
environment.safefunction(Navigator);
environment.rename(Navigator);

Object.defineProperty(Navigator.prototype,"vendorSub",{value: ``,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"productSub",{value: `20030107`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"vendor",{value: `Google Inc.`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"maxTouchPoints",{value: 0,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"scheduling",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"userActivation",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"doNotTrack",{value: null,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"geolocation",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"connection",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"plugins",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"mimeTypes",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"pdfViewerEnabled",{value: true,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"webkitTemporaryStorage",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"webkitPersistentStorage",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"hardwareConcurrency",{value: 8,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"cookieEnabled",{value: true,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"appCodeName",{value: `Mozilla`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"appName",{value: `Netscape`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"appVersion",{value: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"platform",{value: `Win32`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"product",{value: `Gecko`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"userAgent",{value: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"language",{value: `zh-CN`,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"languages",{value: [],writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"onLine",{value: true,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"webdriver",{value: false,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"getGamepads",{value: function getGamepads(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"javaEnabled",{value: function javaEnabled(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"sendBeacon",{value: function sendBeacon(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"vibrate",{value: function vibrate(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"bluetooth",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"clipboard",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"credentials",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"keyboard",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"managed",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"mediaDevices",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"storage",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"serviceWorker",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"wakeLock",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"deviceMemory",{value: 8,writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"ink",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"hid",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"locks",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"mediaCapabilities",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"mediaSession",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"permissions",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"presentation",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"serial",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"virtualKeyboard",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"usb",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"xr",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"userAgentData",{value: {},writable:undefined,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"canShare",{value: function canShare(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"share",{value: function share(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"clearAppBadge",{value: function clearAppBadge(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"setAppBadge",{value: function setAppBadge(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"getBattery",{value: function getBattery(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"getInstalledRelatedApps",{value: function getInstalledRelatedApps(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"getUserMedia",{value: function getUserMedia(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"requestMIDIAccess",{value: function requestMIDIAccess(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"requestMediaKeySystemAccess",{value: function requestMediaKeySystemAccess(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"webkitGetUserMedia",{value: function webkitGetUserMedia(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"registerProtocolHandler",{value: function registerProtocolHandler(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"unregisterProtocolHandler",{value: function unregisterProtocolHandler(){debugger;},writable:true,enumerable:true,configurable:true});
Object.defineProperty(Navigator.prototype,"Symbol.toStringTag",{value: "Navigator",writable:false,enumerable:false,configurable:true});

environment.safefunction(Node.prototype.appendChild);
environment.rename(Node.prototype.appendChild,"appendChild");
environment.safefunction(Node.prototype.cloneNode);
environment.rename(Node.prototype.cloneNode,"cloneNode");
environment.safefunction(Node.prototype.compareDocumentPosition);
environment.rename(Node.prototype.compareDocumentPosition,"compareDocumentPosition");
environment.safefunction(Node.prototype.contains);
environment.rename(Node.prototype.contains,"contains");
environment.safefunction(Node.prototype.getRootNode);
environment.rename(Node.prototype.getRootNode,"getRootNode");
environment.safefunction(Node.prototype.hasChildNodes);
environment.rename(Node.prototype.hasChildNodes,"hasChildNodes");
environment.safefunction(Node.prototype.insertBefore);
environment.rename(Node.prototype.insertBefore,"insertBefore");
environment.safefunction(Node.prototype.isDefaultNamespace);
environment.rename(Node.prototype.isDefaultNamespace,"isDefaultNamespace");
environment.safefunction(Node.prototype.isEqualNode);
environment.rename(Node.prototype.isEqualNode,"isEqualNode");
environment.safefunction(Node.prototype.isSameNode);
environment.rename(Node.prototype.isSameNode,"isSameNode");
environment.safefunction(Node.prototype.lookupNamespaceURI);
environment.rename(Node.prototype.lookupNamespaceURI,"lookupNamespaceURI");
environment.safefunction(Node.prototype.lookupPrefix);
environment.rename(Node.prototype.lookupPrefix,"lookupPrefix");
environment.safefunction(Node.prototype.normalize);
environment.rename(Node.prototype.normalize,"normalize");
environment.safefunction(Node.prototype.removeChild);
environment.rename(Node.prototype.removeChild,"removeChild");
environment.safefunction(Node.prototype.replaceChild);
environment.rename(Node.prototype.replaceChild,"replaceChild");
environment.safefunction(Navigator.prototype.getGamepads);
environment.rename(Navigator.prototype.getGamepads,"getGamepads");
environment.safefunction(Navigator.prototype.javaEnabled);
environment.rename(Navigator.prototype.javaEnabled,"javaEnabled");
environment.safefunction(Navigator.prototype.sendBeacon);
environment.rename(Navigator.prototype.sendBeacon,"sendBeacon");
environment.safefunction(Navigator.prototype.vibrate);
environment.rename(Navigator.prototype.vibrate,"vibrate");
environment.safefunction(Navigator.prototype.canShare);
environment.rename(Navigator.prototype.canShare,"canShare");
environment.safefunction(Navigator.prototype.share);
environment.rename(Navigator.prototype.share,"share");
environment.safefunction(Navigator.prototype.clearAppBadge);
environment.rename(Navigator.prototype.clearAppBadge,"clearAppBadge");
environment.safefunction(Navigator.prototype.setAppBadge);
environment.rename(Navigator.prototype.setAppBadge,"setAppBadge");
environment.safefunction(Navigator.prototype.getBattery);
environment.rename(Navigator.prototype.getBattery,"getBattery");
environment.safefunction(Navigator.prototype.getInstalledRelatedApps);
environment.rename(Navigator.prototype.getInstalledRelatedApps,"getInstalledRelatedApps");
environment.safefunction(Navigator.prototype.getUserMedia);
environment.rename(Navigator.prototype.getUserMedia,"getUserMedia");
environment.safefunction(Navigator.prototype.requestMIDIAccess);
environment.rename(Navigator.prototype.requestMIDIAccess,"requestMIDIAccess");
environment.safefunction(Navigator.prototype.requestMediaKeySystemAccess);
environment.rename(Navigator.prototype.requestMediaKeySystemAccess,"requestMediaKeySystemAccess");
environment.safefunction(Navigator.prototype.webkitGetUserMedia);
environment.rename(Navigator.prototype.webkitGetUserMedia,"webkitGetUserMedia");
environment.safefunction(Navigator.prototype.registerProtocolHandler);
environment.rename(Navigator.prototype.registerProtocolHandler,"registerProtocolHandler");
environment.safefunction(Navigator.prototype.unregisterProtocolHandler);
environment.rename(Navigator.prototype.unregisterProtocolHandler,"unregisterProtocolHandler");

navigator = {}

environment.safefunction(location.assign);
environment.rename(location.assign,"assign");
environment.safefunction(location.reload);
environment.rename(location.reload,"reload");
environment.safefunction(location.replace);
environment.rename(location.replace,"replace");
Object.setPrototypeOf(navigator, Navigator.prototype);
navigator = environment.proxy(navigator, "navigator");
